#!/usr/bin/env python
"""Combine a set of ablation eval_results.json files (from runs trained
with `train.py --tag ... --override ...`) into a LaTeX table at
paper/tables/ablation_table.tex.

Usage:
    python scripts/make_ablation_table.py --dataset ped2 --rows \
        "Baseline (gate on, $N{=}128$, $a\\in[.9,.999]$)=results/ped2/eval_results.json" \
        "Gate off=results/ped2_nogate/eval_results.json" \
        "Decay fast $a\\in[.5,.9]$=results/ped2_decayfast/eval_results.json" \
        "Decay slow $a\\in[.98,.9999]$=results/ped2_decayslow/eval_results.json" \
        "State size $N{=}32$=results/ped2_state32/eval_results.json" \
        "State size $N{=}256$=results/ped2_state256/eval_results.json"
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", required=True, help="dataset label for the caption")
    parser.add_argument("--rows", nargs="+", required=True,
                         help='one or more "Label=path/to/eval_results.json" entries')
    parser.add_argument("--out", default="paper/tables/ablation_table.tex", type=Path)
    parser.add_argument("--label", default=None,
                         help="LaTeX \\label key; defaults to tab:ablation-<slugified dataset>. "
                              "Must be unique across every table \\input by the same document — "
                              "one ablation table per dataset means one label each.")
    args = parser.parse_args()

    label = args.label or f"tab:ablation-{args.dataset.lower().replace(' ', '-')}"

    lines = []
    lines.append("% Auto-generated by scripts/make_ablation_table.py — do not edit by hand.")
    lines.append("\\begin{table*}[t]")
    lines.append("\\centering")
    lines.append(f"\\caption{{Ablations on {args.dataset}: architectural variants, all else "
                  "held fixed. Latency/FPS measured the same way as Table~\\ref{tab:main}.}")
    lines.append(f"\\label{{{label}}}")
    lines.append("\\resizebox{\\linewidth}{!}{%")
    lines.append("\\small")
    lines.append("\\begin{tabular}{lcccc}")
    lines.append("\\toprule")
    lines.append("Variant & Frame-AUC$\\uparrow$ & EER$\\downarrow$ & "
                  "Latency (ms)$\\downarrow$ & FPS$\\uparrow$ \\\\")
    lines.append("\\midrule")

    for row in args.rows:
        # rpartition (not partition): labels may themselves contain "="
        # (e.g. "N=128"), but result paths never do.
        label, _, path = row.rpartition("=")
        with open(path) as f:
            d = json.load(f)
        lines.append(
            f"{label} & {100*d['frame_auc']:.1f} & {100*d['eer']:.1f} & "
            f"{d['latency_ms_mean']:.2f} & {d['fps']:.0f} \\\\"
        )

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("}")
    lines.append("\\end{table*}")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out}")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
