#!/usr/bin/env python
"""Combine one or more results/<dataset>/theory_analysis.json files (each
produced by scripts/analyze_theory.py) into a single LaTeX table at
paper/tables/theory_table.tex. Mirrors make_latex_table.py's pattern:
re-run this any time you re-run analyze_theory.py for any dataset — this
script is the only thing that should touch theory_table.tex.

Usage:
    python scripts/make_theory_table.py --results \
        results/ped2/theory_analysis.json \
        results/avenue/theory_analysis.json \
        results/shanghaitech/theory_analysis.json
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

DATASET_LABELS = {
    "ped2": "UCSD Ped2",
    "avenue": "CUHK Avenue",
    "shanghaitech": "ShanghaiTech",
}


def fmt(x, decimals=1):
    return "--" if x is None else f"{x:.{decimals}f}"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--results", nargs="+", required=True, type=Path)
    parser.add_argument("--out", default="paper/tables/theory_table.tex", type=Path)
    args = parser.parse_args()

    entries = []
    for p in args.results:
        with open(p) as f:
            entries.append(json.load(f))

    lines = []
    lines.append("% Auto-generated by scripts/make_theory_table.py — do not edit by hand.")
    lines.append("\\begin{table*}[t]")
    lines.append("\\centering")
    lines.append("\\caption{Predicted settling delay (Eq.~\\ref{eq:delay-bound}), from each "
                  "dataset's trained mean decay, vs.\\ empirically measured detection delay.}")
    lines.append("\\label{tab:theory}")
    lines.append("\\resizebox{\\linewidth}{!}{%")
    lines.append("\\small")
    lines.append("\\begin{tabular}{llccc}")
    lines.append("\\toprule")
    lines.append("Dataset & Layer & Mean decay $a$ & Theory delay (frames) & "
                  "Empirical delay (frames) \\\\")
    lines.append("\\midrule")

    for e in entries:
        ds_label = DATASET_LABELS.get(e["dataset"], e["dataset"])
        mean_decays = e["mean_base_decay_per_layer"]
        delay_theory = e["theoretical_settling_delay_frames"]
        emp = e.get("empirical_mean_delay_frames")
        n = e.get("num_clips_with_delay", 0)

        for i, a in enumerate(mean_decays):
            emp_cell = f"{fmt(emp)} ($n{{=}}${n})" if i == 0 else ""
            lines.append(
                f"{ds_label if i == 0 else ''} & {i} & {a:.4f} & "
                f"{fmt(delay_theory[f'layer_{i}'])} & {emp_cell} \\\\"
            )
        lines.append("\\midrule")

    if lines[-1] == "\\midrule":
        lines.pop()
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("}")
    lines.append("\\end{table*}")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out}")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
