#!/usr/bin/env python
"""Turn evaluate.py's eval_results.json outputs into a LaTeX results table,
written to paper/tables/results_table.tex and included by
paper/sections/experiments.tex. Re-run any time you re-evaluate — this
script is the only thing that should ever touch that .tex file.

Usage:
    python scripts/make_latex_table.py \
        --results results/ped2/eval_results.json \
                   results/avenue/eval_results.json \
                   results/shanghaitech/eval_results.json
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

DATASET_LABELS = {
    "ped2": "UCSD Ped2",
    "avenue": "CUHK Avenue",
    "shanghaitech": "ShanghaiTech",
}


def fmt(x, pct=True):
    if x is None:
        return "--"
    return f"{100*x:.1f}" if pct else f"{x:.2f}"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--results", nargs="+", required=True, type=Path)
    parser.add_argument("--out", default="paper/tables/results_table.tex", type=Path)
    args = parser.parse_args()

    entries = []
    for p in args.results:
        with open(p) as f:
            entries.append(json.load(f))

    lines = []
    lines.append("% Auto-generated by scripts/make_latex_table.py — do not edit by hand.")
    lines.append("\\begin{table*}[t]")
    lines.append("\\centering")
    lines.append("\\caption{Main results: standard accuracy metrics alongside on-device "
                  "streaming latency/throughput.}")
    lines.append("\\label{tab:main}")
    lines.append("\\resizebox{\\linewidth}{!}{%")
    lines.append("\\small")
    lines.append("\\begin{tabular}{llccccc}")
    lines.append("\\toprule")
    lines.append("Dataset & Method & Frame-AUC$\\uparrow$ & EER$\\downarrow$ & "
                  "Latency (ms)$\\downarrow$ & FPS$\\uparrow$ & Hardware \\\\")
    lines.append("\\midrule")

    for e in entries:
        ds_key = e["dataset"]
        ds_label = DATASET_LABELS.get(ds_key, ds_key)

        lines.append(
            f"{ds_label} & Ours (streaming SSM) & "
            f"{fmt(e.get('frame_auc'))} & {fmt(e.get('eer'))} & "
            f"{fmt(e.get('latency_ms_mean'), pct=False)} & "
            f"{fmt(e.get('fps'), pct=False)} & {e.get('device', '--')} \\\\"
        )

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("}")
    lines.append("\\end{table*}")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out}")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
